# Generated by Django 4.1.7 on 2023-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='No name', max_length=200, null=True),
        ),
    ]
