# Generated by Django 4.1.7 on 2023-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.URLField(default='No image', null=True),
        ),
    ]
