# Generated by Django 4.1.5 on 2023-03-18 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Добавлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название криптовалюты')),
                ('name_id', models.CharField(max_length=100, verbose_name='Символьное название')),
                ('price', models.CharField(max_length=100, verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
