# Generated by Django 4.1.5 on 2023-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='slug',
            field=models.SlugField(default=0, max_length=100, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
