# Generated by Django 4.1.5 on 2023-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0002_favorites_slug_alter_favorites_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.IntegerField(verbose_name='id_пользователя'),
        ),
    ]
