# Generated by Django 4.1.5 on 2023-03-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0003_alter_favorites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_pk',
        ),
    ]
