# Generated by Django 4.1.5 on 2023-03-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0004_rename_user_favorites_user_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_percentage_change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='name_id',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='price',
        ),
        migrations.AddField(
            model_name='favorites',
            name='cryptocurrencies',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrencies.cryptocurrencies'),
            preserve_default=False,
        ),
    ]
