# Generated by Django 4.1.7 on 2023-03-26 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0006_alter_cryptocurrencies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrencies',
            options={},
        ),
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='added',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 3, 26, 11, 53, 30, 367571)),
        ),
    ]
