# Generated by Django 4.1.7 on 2023-03-26 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0007_alter_cryptocurrencies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='added',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 3, 26, 12, 27, 20, 890579)),
        ),
    ]
